name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - "docs/**"
    - "mkdocs.yml"
    - "README.md"
    - ".gitignore"
    - "LICENSE"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - "docs/**"
    - "mkdocs.yml"
    - "README.md"
    - ".gitignore"
    - "LICENSE"
jobs:
  run:
    name: "Run Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Run pylint
      run: |
        pylint src

    - name: Run black
      run: |
        black --check src

    - name: Run tests
      run: |
        pytest tests